# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_ds(__cs__.cstruct):
    class _USER_PROPERTY(__cs__.Structure):
        NameLength: _c_ds.uint16
        ValueLength: _c_ds.uint16
        PropertyFlag: _c_ds.uint16
        PropertyName: __cs__.WcharArray
        PropertyValue: __cs__.CharArray
        @overload
        def __init__(
            self,
            NameLength: _c_ds.uint16 | None = ...,
            ValueLength: _c_ds.uint16 | None = ...,
            PropertyFlag: _c_ds.uint16 | None = ...,
            PropertyName: __cs__.WcharArray | None = ...,
            PropertyValue: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    USER_PROPERTY: TypeAlias = _USER_PROPERTY
    class _USER_PROPERTIES_HEADER(__cs__.Structure):
        Reserved1: _c_ds.uint32
        Length: _c_ds.uint32
        Reserved2: _c_ds.uint16
        Reserved3: _c_ds.uint16
        Reserved4: __cs__.CharArray
        PropertySignature: _c_ds.uint16
        PropertyCount: _c_ds.uint16
        @overload
        def __init__(
            self,
            Reserved1: _c_ds.uint32 | None = ...,
            Length: _c_ds.uint32 | None = ...,
            Reserved2: _c_ds.uint16 | None = ...,
            Reserved3: _c_ds.uint16 | None = ...,
            Reserved4: __cs__.CharArray | None = ...,
            PropertySignature: _c_ds.uint16 | None = ...,
            PropertyCount: _c_ds.uint16 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    USER_PROPERTIES_HEADER: TypeAlias = _USER_PROPERTIES_HEADER
    class _ADAM_PROPERTIES_HEADER(__cs__.Structure):
        Reserved1: _c_ds.uint32
        Reserved2: _c_ds.uint32
        Reserved3: _c_ds.uint32
        Reserved4: _c_ds.uint32
        Reserved5: _c_ds.uint32
        Reserved6: _c_ds.uint32
        @overload
        def __init__(
            self,
            Reserved1: _c_ds.uint32 | None = ...,
            Reserved2: _c_ds.uint32 | None = ...,
            Reserved3: _c_ds.uint32 | None = ...,
            Reserved4: _c_ds.uint32 | None = ...,
            Reserved5: _c_ds.uint32 | None = ...,
            Reserved6: _c_ds.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    ADAM_PROPERTIES_HEADER: TypeAlias = _ADAM_PROPERTIES_HEADER
    class _KERB_KEY_DATA(__cs__.Structure):
        Reserved1: _c_ds.uint16
        Reserved2: _c_ds.uint16
        Reserved3: _c_ds.uint32
        KeyType: _c_ds.uint32
        KeyLength: _c_ds.uint32
        KeyOffset: _c_ds.uint32
        @overload
        def __init__(
            self,
            Reserved1: _c_ds.uint16 | None = ...,
            Reserved2: _c_ds.uint16 | None = ...,
            Reserved3: _c_ds.uint32 | None = ...,
            KeyType: _c_ds.uint32 | None = ...,
            KeyLength: _c_ds.uint32 | None = ...,
            KeyOffset: _c_ds.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    KERB_KEY_DATA: TypeAlias = _KERB_KEY_DATA
    class _KERB_STORED_CREDENTIAL(__cs__.Structure):
        Revision: _c_ds.uint16
        Flags: _c_ds.uint16
        CredentialCount: _c_ds.uint16
        OldCredentialCount: _c_ds.uint16
        DefaultSaltLength: _c_ds.uint16
        DefaultSaltMaximumLength: _c_ds.uint16
        DefaultSaltOffset: _c_ds.uint32
        class _KERB_KEY_DATA(__cs__.Structure):
            Reserved1: _c_ds.uint16
            Reserved2: _c_ds.uint16
            Reserved3: _c_ds.uint32
            KeyType: _c_ds.uint32
            KeyLength: _c_ds.uint32
            KeyOffset: _c_ds.uint32
            @overload
            def __init__(
                self,
                Reserved1: _c_ds.uint16 | None = ...,
                Reserved2: _c_ds.uint16 | None = ...,
                Reserved3: _c_ds.uint32 | None = ...,
                KeyType: _c_ds.uint32 | None = ...,
                KeyLength: _c_ds.uint32 | None = ...,
                KeyOffset: _c_ds.uint32 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        Credentials: __cs__.Array[_KERB_KEY_DATA]
        class _KERB_KEY_DATA(__cs__.Structure):
            Reserved1: _c_ds.uint16
            Reserved2: _c_ds.uint16
            Reserved3: _c_ds.uint32
            KeyType: _c_ds.uint32
            KeyLength: _c_ds.uint32
            KeyOffset: _c_ds.uint32
            @overload
            def __init__(
                self,
                Reserved1: _c_ds.uint16 | None = ...,
                Reserved2: _c_ds.uint16 | None = ...,
                Reserved3: _c_ds.uint32 | None = ...,
                KeyType: _c_ds.uint32 | None = ...,
                KeyLength: _c_ds.uint32 | None = ...,
                KeyOffset: _c_ds.uint32 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        OldCredentials: __cs__.Array[_KERB_KEY_DATA]
        @overload
        def __init__(
            self,
            Revision: _c_ds.uint16 | None = ...,
            Flags: _c_ds.uint16 | None = ...,
            CredentialCount: _c_ds.uint16 | None = ...,
            OldCredentialCount: _c_ds.uint16 | None = ...,
            DefaultSaltLength: _c_ds.uint16 | None = ...,
            DefaultSaltMaximumLength: _c_ds.uint16 | None = ...,
            DefaultSaltOffset: _c_ds.uint32 | None = ...,
            Credentials: __cs__.Array[_KERB_KEY_DATA] | None = ...,
            OldCredentials: __cs__.Array[_KERB_KEY_DATA] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    KERB_STORED_CREDENTIAL: TypeAlias = _KERB_STORED_CREDENTIAL
    class _KERB_KEY_DATA_NEW(__cs__.Structure):
        Reserved1: _c_ds.uint16
        Reserved2: _c_ds.uint16
        Reserved3: _c_ds.uint32
        IterationCount: _c_ds.uint32
        KeyType: _c_ds.uint32
        KeyLength: _c_ds.uint32
        KeyOffset: _c_ds.uint32
        @overload
        def __init__(
            self,
            Reserved1: _c_ds.uint16 | None = ...,
            Reserved2: _c_ds.uint16 | None = ...,
            Reserved3: _c_ds.uint32 | None = ...,
            IterationCount: _c_ds.uint32 | None = ...,
            KeyType: _c_ds.uint32 | None = ...,
            KeyLength: _c_ds.uint32 | None = ...,
            KeyOffset: _c_ds.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    KERB_KEY_DATA_NEW: TypeAlias = _KERB_KEY_DATA_NEW
    class _KERB_STORED_CREDENTIAL_NEW(__cs__.Structure):
        Revision: _c_ds.uint16
        Flags: _c_ds.uint16
        CredentialCount: _c_ds.uint16
        ServiceCredentialCount: _c_ds.uint16
        OldCredentialCount: _c_ds.uint16
        OlderCredentialCount: _c_ds.uint16
        DefaultSaltLength: _c_ds.uint16
        DefaultSaltMaximumLength: _c_ds.uint16
        DefaultSaltOffset: _c_ds.uint32
        DefaultIterationCount: _c_ds.uint32
        class _KERB_KEY_DATA_NEW(__cs__.Structure):
            Reserved1: _c_ds.uint16
            Reserved2: _c_ds.uint16
            Reserved3: _c_ds.uint32
            IterationCount: _c_ds.uint32
            KeyType: _c_ds.uint32
            KeyLength: _c_ds.uint32
            KeyOffset: _c_ds.uint32
            @overload
            def __init__(
                self,
                Reserved1: _c_ds.uint16 | None = ...,
                Reserved2: _c_ds.uint16 | None = ...,
                Reserved3: _c_ds.uint32 | None = ...,
                IterationCount: _c_ds.uint32 | None = ...,
                KeyType: _c_ds.uint32 | None = ...,
                KeyLength: _c_ds.uint32 | None = ...,
                KeyOffset: _c_ds.uint32 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        Credentials: __cs__.Array[_KERB_KEY_DATA_NEW]
        class _KERB_KEY_DATA_NEW(__cs__.Structure):
            Reserved1: _c_ds.uint16
            Reserved2: _c_ds.uint16
            Reserved3: _c_ds.uint32
            IterationCount: _c_ds.uint32
            KeyType: _c_ds.uint32
            KeyLength: _c_ds.uint32
            KeyOffset: _c_ds.uint32
            @overload
            def __init__(
                self,
                Reserved1: _c_ds.uint16 | None = ...,
                Reserved2: _c_ds.uint16 | None = ...,
                Reserved3: _c_ds.uint32 | None = ...,
                IterationCount: _c_ds.uint32 | None = ...,
                KeyType: _c_ds.uint32 | None = ...,
                KeyLength: _c_ds.uint32 | None = ...,
                KeyOffset: _c_ds.uint32 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        ServiceCredentials: __cs__.Array[_KERB_KEY_DATA_NEW]
        class _KERB_KEY_DATA_NEW(__cs__.Structure):
            Reserved1: _c_ds.uint16
            Reserved2: _c_ds.uint16
            Reserved3: _c_ds.uint32
            IterationCount: _c_ds.uint32
            KeyType: _c_ds.uint32
            KeyLength: _c_ds.uint32
            KeyOffset: _c_ds.uint32
            @overload
            def __init__(
                self,
                Reserved1: _c_ds.uint16 | None = ...,
                Reserved2: _c_ds.uint16 | None = ...,
                Reserved3: _c_ds.uint32 | None = ...,
                IterationCount: _c_ds.uint32 | None = ...,
                KeyType: _c_ds.uint32 | None = ...,
                KeyLength: _c_ds.uint32 | None = ...,
                KeyOffset: _c_ds.uint32 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        OldCredentials: __cs__.Array[_KERB_KEY_DATA_NEW]
        class _KERB_KEY_DATA_NEW(__cs__.Structure):
            Reserved1: _c_ds.uint16
            Reserved2: _c_ds.uint16
            Reserved3: _c_ds.uint32
            IterationCount: _c_ds.uint32
            KeyType: _c_ds.uint32
            KeyLength: _c_ds.uint32
            KeyOffset: _c_ds.uint32
            @overload
            def __init__(
                self,
                Reserved1: _c_ds.uint16 | None = ...,
                Reserved2: _c_ds.uint16 | None = ...,
                Reserved3: _c_ds.uint32 | None = ...,
                IterationCount: _c_ds.uint32 | None = ...,
                KeyType: _c_ds.uint32 | None = ...,
                KeyLength: _c_ds.uint32 | None = ...,
                KeyOffset: _c_ds.uint32 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        OlderCredentials: __cs__.Array[_KERB_KEY_DATA_NEW]
        @overload
        def __init__(
            self,
            Revision: _c_ds.uint16 | None = ...,
            Flags: _c_ds.uint16 | None = ...,
            CredentialCount: _c_ds.uint16 | None = ...,
            ServiceCredentialCount: _c_ds.uint16 | None = ...,
            OldCredentialCount: _c_ds.uint16 | None = ...,
            OlderCredentialCount: _c_ds.uint16 | None = ...,
            DefaultSaltLength: _c_ds.uint16 | None = ...,
            DefaultSaltMaximumLength: _c_ds.uint16 | None = ...,
            DefaultSaltOffset: _c_ds.uint32 | None = ...,
            DefaultIterationCount: _c_ds.uint32 | None = ...,
            Credentials: __cs__.Array[_KERB_KEY_DATA_NEW] | None = ...,
            ServiceCredentials: __cs__.Array[_KERB_KEY_DATA_NEW] | None = ...,
            OldCredentials: __cs__.Array[_KERB_KEY_DATA_NEW] | None = ...,
            OlderCredentials: __cs__.Array[_KERB_KEY_DATA_NEW] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    KERB_STORED_CREDENTIAL_NEW: TypeAlias = _KERB_STORED_CREDENTIAL_NEW
    class _WDIGEST_CREDENTIALS(__cs__.Structure):
        Reserved1: _c_ds.uint8
        Reserved2: _c_ds.uint8
        Version: _c_ds.uint8
        NumberOfHashes: _c_ds.uint8
        Reserved3: __cs__.CharArray
        Hash: __cs__.Array[__cs__.CharArray]
        @overload
        def __init__(
            self,
            Reserved1: _c_ds.uint8 | None = ...,
            Reserved2: _c_ds.uint8 | None = ...,
            Version: _c_ds.uint8 | None = ...,
            NumberOfHashes: _c_ds.uint8 | None = ...,
            Reserved3: __cs__.CharArray | None = ...,
            Hash: __cs__.Array[__cs__.CharArray] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    WDIGEST_CREDENTIALS: TypeAlias = _WDIGEST_CREDENTIALS

# Technically `c_ds` is an instance of `_c_ds`, but then we can't use it in type hints
c_ds: TypeAlias = _c_ds
