# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_pek(__cs__.cstruct):
    PEK_PRE_2012R2_VERSION: Literal[2] = ...
    PEK_2016_TP4_VERSION: Literal[3] = ...
    PEK_ENCRYPTION: Literal[16] = ...
    PEK_ENCRYPTION_WITH_SALT: Literal[17] = ...
    PEK_ENCRYPTION_WITH_AES: Literal[19] = ...
    FILETIME: TypeAlias = _c_pek.uint64
    class _ENCRYPTED_PEK_LIST(__cs__.Structure):
        Version: _c_pek.uint32
        BootOption: _c_pek.uint32
        Salt: __cs__.CharArray
        EncryptedData: __cs__.CharArray
        @overload
        def __init__(
            self,
            Version: _c_pek.uint32 | None = ...,
            BootOption: _c_pek.uint32 | None = ...,
            Salt: __cs__.CharArray | None = ...,
            EncryptedData: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    ENCRYPTED_PEK_LIST: TypeAlias = _ENCRYPTED_PEK_LIST
    class _PEK(__cs__.Structure):
        KeyId: _c_pek.uint32
        Key: __cs__.CharArray
        @overload
        def __init__(self, KeyId: _c_pek.uint32 | None = ..., Key: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    PEK: TypeAlias = _PEK
    class _CLEAR_PEK_LIST(__cs__.Structure):
        Authenticator: __cs__.CharArray
        LastKeyGenerationTime: _c_pek.uint64
        CurrentKey: _c_pek.uint32
        CountOfKeys: _c_pek.uint32
        class _PEK(__cs__.Structure):
            KeyId: _c_pek.uint32
            Key: __cs__.CharArray
            @overload
            def __init__(self, KeyId: _c_pek.uint32 | None = ..., Key: __cs__.CharArray | None = ...): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        PekArray: __cs__.Array[_PEK]
        @overload
        def __init__(
            self,
            Authenticator: __cs__.CharArray | None = ...,
            LastKeyGenerationTime: _c_pek.uint64 | None = ...,
            CurrentKey: _c_pek.uint32 | None = ...,
            CountOfKeys: _c_pek.uint32 | None = ...,
            PekArray: __cs__.Array[_PEK] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    CLEAR_PEK_LIST: TypeAlias = _CLEAR_PEK_LIST
    class _ENCRYPTED_DATA(__cs__.Structure):
        AlgorithmId: _c_pek.uint16
        Flags: _c_pek.uint16
        KeyId: _c_pek.uint32
        EncryptedData: __cs__.CharArray
        @overload
        def __init__(
            self,
            AlgorithmId: _c_pek.uint16 | None = ...,
            Flags: _c_pek.uint16 | None = ...,
            KeyId: _c_pek.uint32 | None = ...,
            EncryptedData: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    ENCRYPTED_DATA: TypeAlias = _ENCRYPTED_DATA
    class _ENCRYPTED_DATA_WITH_SALT(__cs__.Structure):
        AlgorithmId: _c_pek.uint16
        Flags: _c_pek.uint16
        KeyId: _c_pek.uint32
        Salt: __cs__.CharArray
        EncryptedData: __cs__.CharArray
        @overload
        def __init__(
            self,
            AlgorithmId: _c_pek.uint16 | None = ...,
            Flags: _c_pek.uint16 | None = ...,
            KeyId: _c_pek.uint32 | None = ...,
            Salt: __cs__.CharArray | None = ...,
            EncryptedData: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    ENCRYPTED_DATA_WITH_SALT: TypeAlias = _ENCRYPTED_DATA_WITH_SALT
    class _ENCRYPTED_DATA_WITH_AES(__cs__.Structure):
        AlgorithmId: _c_pek.uint16
        Flags: _c_pek.uint16
        KeyId: _c_pek.uint32
        IV: __cs__.CharArray
        Length: _c_pek.uint32
        EncryptedData: __cs__.CharArray
        @overload
        def __init__(
            self,
            AlgorithmId: _c_pek.uint16 | None = ...,
            Flags: _c_pek.uint16 | None = ...,
            KeyId: _c_pek.uint32 | None = ...,
            IV: __cs__.CharArray | None = ...,
            Length: _c_pek.uint32 | None = ...,
            EncryptedData: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    ENCRYPTED_DATA_WITH_AES: TypeAlias = _ENCRYPTED_DATA_WITH_AES

# Technically `c_pek` is an instance of `_c_pek`, but then we can't use it in type hints
c_pek: TypeAlias = _c_pek
