# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, overload

import dissect.cstruct as __cs__
from typing_extensions import TypeAlias

class _c_qnx6(__cs__.cstruct):
    QNX4_SUPER_MAGIC: Literal[47] = ...
    QNX6_SUPER_MAGIC: Literal[1746473250] = ...
    QNX6_ROOT_INO: Literal[1] = ...
    QNX6_FILE_DIRECTORY: Literal[1] = ...
    QNX6_FILE_DELETED: Literal[2] = ...
    QNX6_FILE_NORMAL: Literal[3] = ...
    QNX6_SUPERBLOCK_SIZE: Literal[512] = ...
    QNX6_SUPERBLOCK_AREA: Literal[4096] = ...
    QNX6_BOOTBLOCK_SIZE: Literal[8192] = ...
    QNX6_DIR_ENTRY_SIZE: Literal[32] = ...
    QNX6_INODE_SIZE: Literal[128] = ...
    QNX6_INODE_SIZE_BITS: Literal[7] = ...
    QNX6_NO_DIRECT_POINTERS: Literal[16] = ...
    QNX6_PTR_MAX_LEVELS: Literal[5] = ...
    QNX6_SHORT_NAME_MAX: Literal[27] = ...
    QNX6_LONG_NAME_MAX: Literal[510] = ...
    QNX6_MOUNT_MMI_FS: Literal[65536] = ...
    __fs16: TypeAlias = _c_qnx6.uint16
    __fs32: TypeAlias = _c_qnx6.uint32
    __fs64: TypeAlias = _c_qnx6.uint64
    class qnx6_inode_entry(__cs__.Structure):
        di_size: _c_qnx6.uint64
        di_uid: _c_qnx6.uint32
        di_gid: _c_qnx6.uint32
        di_ftime: _c_qnx6.uint32
        di_mtime: _c_qnx6.uint32
        di_atime: _c_qnx6.uint32
        di_ctime: _c_qnx6.uint32
        di_mode: _c_qnx6.uint16
        di_ext_mode: _c_qnx6.uint16
        di_block_ptr: __cs__.Array[_c_qnx6.uint32]
        di_filelevels: _c_qnx6.uint8
        di_status: _c_qnx6.uint8
        di_unknown2: __cs__.CharArray
        di_zero2: __cs__.CharArray
        @overload
        def __init__(
            self,
            di_size: _c_qnx6.uint64 | None = ...,
            di_uid: _c_qnx6.uint32 | None = ...,
            di_gid: _c_qnx6.uint32 | None = ...,
            di_ftime: _c_qnx6.uint32 | None = ...,
            di_mtime: _c_qnx6.uint32 | None = ...,
            di_atime: _c_qnx6.uint32 | None = ...,
            di_ctime: _c_qnx6.uint32 | None = ...,
            di_mode: _c_qnx6.uint16 | None = ...,
            di_ext_mode: _c_qnx6.uint16 | None = ...,
            di_block_ptr: __cs__.Array[_c_qnx6.uint32] | None = ...,
            di_filelevels: _c_qnx6.uint8 | None = ...,
            di_status: _c_qnx6.uint8 | None = ...,
            di_unknown2: __cs__.CharArray | None = ...,
            di_zero2: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class qnx6_dir_entry(__cs__.Structure):
        de_inode: _c_qnx6.uint32
        de_size: _c_qnx6.uint8
        de_fname: __cs__.CharArray
        @overload
        def __init__(
            self,
            de_inode: _c_qnx6.uint32 | None = ...,
            de_size: _c_qnx6.uint8 | None = ...,
            de_fname: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class qnx6_long_dir_entry(__cs__.Structure):
        de_inode: _c_qnx6.uint32
        de_size: _c_qnx6.uint8
        de_unknown: __cs__.CharArray
        de_long_inode: _c_qnx6.uint32
        de_checksum: _c_qnx6.uint32
        @overload
        def __init__(
            self,
            de_inode: _c_qnx6.uint32 | None = ...,
            de_size: _c_qnx6.uint8 | None = ...,
            de_unknown: __cs__.CharArray | None = ...,
            de_long_inode: _c_qnx6.uint32 | None = ...,
            de_checksum: _c_qnx6.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class qnx6_long_filename(__cs__.Structure):
        lf_size: _c_qnx6.uint16
        lf_fname: __cs__.CharArray
        @overload
        def __init__(self, lf_size: _c_qnx6.uint16 | None = ..., lf_fname: __cs__.CharArray | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class qnx6_root_node(__cs__.Structure):
        size: _c_qnx6.uint64
        ptr: __cs__.Array[_c_qnx6.uint32]
        levels: _c_qnx6.uint8
        mode: _c_qnx6.uint8
        spare: __cs__.CharArray
        @overload
        def __init__(
            self,
            size: _c_qnx6.uint64 | None = ...,
            ptr: __cs__.Array[_c_qnx6.uint32] | None = ...,
            levels: _c_qnx6.uint8 | None = ...,
            mode: _c_qnx6.uint8 | None = ...,
            spare: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class qnx6_super_block(__cs__.Structure):
        sb_magic: _c_qnx6.uint32
        sb_checksum: _c_qnx6.uint32
        sb_serial: _c_qnx6.uint64
        sb_ctime: _c_qnx6.uint32
        sb_atime: _c_qnx6.uint32
        sb_flags: _c_qnx6.uint32
        sb_version1: _c_qnx6.uint16
        sb_version2: _c_qnx6.uint16
        sb_volumeid: __cs__.CharArray
        sb_blocksize: _c_qnx6.uint32
        sb_num_inodes: _c_qnx6.uint32
        sb_free_inodes: _c_qnx6.uint32
        sb_num_blocks: _c_qnx6.uint32
        sb_free_blocks: _c_qnx6.uint32
        sb_allocgroup: _c_qnx6.uint32
        Inode: _c_qnx6.qnx6_root_node
        Bitmap: _c_qnx6.qnx6_root_node
        Longfile: _c_qnx6.qnx6_root_node
        Unknown: _c_qnx6.qnx6_root_node
        @overload
        def __init__(
            self,
            sb_magic: _c_qnx6.uint32 | None = ...,
            sb_checksum: _c_qnx6.uint32 | None = ...,
            sb_serial: _c_qnx6.uint64 | None = ...,
            sb_ctime: _c_qnx6.uint32 | None = ...,
            sb_atime: _c_qnx6.uint32 | None = ...,
            sb_flags: _c_qnx6.uint32 | None = ...,
            sb_version1: _c_qnx6.uint16 | None = ...,
            sb_version2: _c_qnx6.uint16 | None = ...,
            sb_volumeid: __cs__.CharArray | None = ...,
            sb_blocksize: _c_qnx6.uint32 | None = ...,
            sb_num_inodes: _c_qnx6.uint32 | None = ...,
            sb_free_inodes: _c_qnx6.uint32 | None = ...,
            sb_num_blocks: _c_qnx6.uint32 | None = ...,
            sb_free_blocks: _c_qnx6.uint32 | None = ...,
            sb_allocgroup: _c_qnx6.uint32 | None = ...,
            Inode: _c_qnx6.qnx6_root_node | None = ...,
            Bitmap: _c_qnx6.qnx6_root_node | None = ...,
            Longfile: _c_qnx6.qnx6_root_node | None = ...,
            Unknown: _c_qnx6.qnx6_root_node | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class qnx6_mmi_super_block(__cs__.Structure):
        sb_magic: _c_qnx6.uint32
        sb_checksum: _c_qnx6.uint32
        sb_serial: _c_qnx6.uint64
        sb_spare0: __cs__.CharArray
        sb_id: __cs__.CharArray
        sb_blocksize: _c_qnx6.uint32
        sb_num_inodes: _c_qnx6.uint32
        sb_free_inodes: _c_qnx6.uint32
        sb_num_blocks: _c_qnx6.uint32
        sb_free_blocks: _c_qnx6.uint32
        sb_spare1: __cs__.CharArray
        Inode: _c_qnx6.qnx6_root_node
        Bitmap: _c_qnx6.qnx6_root_node
        Longfile: _c_qnx6.qnx6_root_node
        Unknown: _c_qnx6.qnx6_root_node
        @overload
        def __init__(
            self,
            sb_magic: _c_qnx6.uint32 | None = ...,
            sb_checksum: _c_qnx6.uint32 | None = ...,
            sb_serial: _c_qnx6.uint64 | None = ...,
            sb_spare0: __cs__.CharArray | None = ...,
            sb_id: __cs__.CharArray | None = ...,
            sb_blocksize: _c_qnx6.uint32 | None = ...,
            sb_num_inodes: _c_qnx6.uint32 | None = ...,
            sb_free_inodes: _c_qnx6.uint32 | None = ...,
            sb_num_blocks: _c_qnx6.uint32 | None = ...,
            sb_free_blocks: _c_qnx6.uint32 | None = ...,
            sb_spare1: __cs__.CharArray | None = ...,
            Inode: _c_qnx6.qnx6_root_node | None = ...,
            Bitmap: _c_qnx6.qnx6_root_node | None = ...,
            Longfile: _c_qnx6.qnx6_root_node | None = ...,
            Unknown: _c_qnx6.qnx6_root_node | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_qnx6` is an instance of `_c_qnx6`, but then we can't use it in type hints
c_qnx6_le: TypeAlias = _c_qnx6
c_qnx6_be: TypeAlias = _c_qnx6
c_qnx6: TypeAlias = _c_qnx6
