# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_ese(__cs__.cstruct):
    MAX_COMPUTERNAME_LENGTH: Literal[15] = ...
    DBTIME: TypeAlias = _c_ese.int64
    OBJID: TypeAlias = _c_ese.uint32
    PGNO: TypeAlias = _c_ese.uint32
    JET_ENGINEFORMATVERSION: TypeAlias = _c_ese.uint32
    XECHECKSUM: TypeAlias = _c_ese.int64
    class CODEPAGE(__cs__.Enum):
        UNICODE = ...
        WESTERN = ...
        ASCII = ...

    class COMPRESSION_SCHEME(__cs__.Enum):
        COMPRESS_NONE = ...
        COMPRESS_7BITASCII = ...
        COMPRESS_7BITUNICODE = ...
        COMPRESS_XPRESS = ...
        COMPRESS_SCRUB = ...
        COMPRESS_XPRESS9 = ...
        COMPRESS_XPRESS10 = ...

    class JET_coltyp(__cs__.Enum):
        Nil = ...
        Bit = ...
        UnsignedByte = ...
        Short = ...
        Long = ...
        Currency = ...
        IEEESingle = ...
        IEEEDouble = ...
        DateTime = ...
        Binary = ...
        Text = ...
        LongBinary = ...
        LongText = ...
        SLV = ...
        UnsignedLong = ...
        LongLong = ...
        GUID = ...
        UnsignedShort = ...
        Max = ...

    class SYSOBJ(__cs__.Enum):
        Nil = ...
        Table = ...
        Column = ...
        Index = ...
        LongValue = ...
        Callback = ...

    class LOGTIME(__cs__.Structure):
        bSeconds: _c_ese.uint8
        bMinutes: _c_ese.uint8
        bHours: _c_ese.uint8
        bDay: _c_ese.uint8
        bMonth: _c_ese.uint8
        bYear: _c_ese.uint8
        fTimeIsUTC: _c_ese.uint8
        bMillisecondsLow: _c_ese.uint8
        fReserved: _c_ese.uint8
        bMillisecondsHigh: _c_ese.uint8
        fUnused: _c_ese.uint8
        @overload
        def __init__(
            self,
            bSeconds: _c_ese.uint8 | None = ...,
            bMinutes: _c_ese.uint8 | None = ...,
            bHours: _c_ese.uint8 | None = ...,
            bDay: _c_ese.uint8 | None = ...,
            bMonth: _c_ese.uint8 | None = ...,
            bYear: _c_ese.uint8 | None = ...,
            fTimeIsUTC: _c_ese.uint8 | None = ...,
            bMillisecondsLow: _c_ese.uint8 | None = ...,
            fReserved: _c_ese.uint8 | None = ...,
            bMillisecondsHigh: _c_ese.uint8 | None = ...,
            fUnused: _c_ese.uint8 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class LGPOS(__cs__.Structure):
        ib: _c_ese.uint16
        isec: _c_ese.uint16
        lGeneration: _c_ese.int32
        @overload
        def __init__(
            self,
            ib: _c_ese.uint16 | None = ...,
            isec: _c_ese.uint16 | None = ...,
            lGeneration: _c_ese.int32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SIGNATURE(__cs__.Structure):
        ulRandom: _c_ese.uint32
        logtimeCreate: _c_ese.LOGTIME
        szComputerName: __cs__.CharArray
        @overload
        def __init__(
            self,
            ulRandom: _c_ese.uint32 | None = ...,
            logtimeCreate: _c_ese.LOGTIME | None = ...,
            szComputerName: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class BKINFOTYPE(__cs__.Enum):
        backupNormal = ...
        backupOSSnapshot = ...
        backupSnapshot = ...
        backupSurrogate = ...

    class BKINFO(__cs__.Structure):
        lgposMark: _c_ese.LGPOS
        logtimeMark: _c_ese.LOGTIME
        genLow: _c_ese.uint32
        genHigh: _c_ese.uint32
        @overload
        def __init__(
            self,
            lgposMark: _c_ese.LGPOS | None = ...,
            logtimeMark: _c_ese.LOGTIME | None = ...,
            genLow: _c_ese.uint32 | None = ...,
            genHigh: _c_ese.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class DBFILEHDR(__cs__.Structure):
        ulChecksum: _c_ese.uint32
        ulMagic: _c_ese.uint32
        ulVersion: _c_ese.uint32
        attrib: _c_ese.int32
        dbtimeDirtied: _c_ese.int64
        signDb: _c_ese.SIGNATURE
        dbstate: _c_ese.uint32
        lgposConsistent: _c_ese.LGPOS
        logtimeConsistent: _c_ese.LOGTIME
        logtimeAttach: _c_ese.LOGTIME
        lgposAttach: _c_ese.LGPOS
        logtimeDetach: _c_ese.LOGTIME
        lgposDetach: _c_ese.LGPOS
        dbid: _c_ese.uint32
        signLog: _c_ese.SIGNATURE
        bkinfoFullPrev: _c_ese.BKINFO
        bkinfoIncPrev: _c_ese.BKINFO
        bkinfoFullCur: _c_ese.BKINFO
        m_ulDbFlags: _c_ese.uint32
        m_rgbDbFlags: __cs__.Array[_c_ese.uint8]
        objidLast: _c_ese.uint32
        dwMajorVersion: _c_ese.uint32
        dwMinorVersion: _c_ese.uint32
        dwBuildNumber: _c_ese.uint32
        lSPNumber: _c_ese.int32
        ulDaeUpdateMajor: _c_ese.uint32
        cbPageSize: _c_ese.uint32
        ulRepairCount: _c_ese.uint32
        logtimeRepair: _c_ese.LOGTIME
        rgbReservedSignSLV: __cs__.Array[_c_ese.uint8]
        dbtimeLastScrub: _c_ese.int64
        logtimeScrub: _c_ese.LOGTIME
        lGenMinRequired: _c_ese.int32
        lGenMaxRequired: _c_ese.int32
        cpgUpgrade55Format: _c_ese.int32
        cpgUpgradeFreePages: _c_ese.int32
        cpgUpgradeSpaceMapPages: _c_ese.int32
        bkinfoSnapshotCur: _c_ese.BKINFO
        ulCreateVersion: _c_ese.uint32
        ulCreateUpdate: _c_ese.uint32
        logtimeGenMaxCreate: _c_ese.LOGTIME
        bkinfoTypeFullPrev: _c_ese.BKINFOTYPE
        bkinfoTypeIncPrev: _c_ese.BKINFOTYPE
        ulRepairCountOld: _c_ese.uint32
        ulECCFixSuccess: _c_ese.uint32
        logtimeECCFixSuccess: _c_ese.LOGTIME
        ulECCFixSuccessOld: _c_ese.uint32
        ulECCFixFail: _c_ese.uint32
        logtimeECCFixFail: _c_ese.LOGTIME
        ulECCFixFailOld: _c_ese.uint32
        ulBadChecksum: _c_ese.uint32
        logtimeBadChecksum: _c_ese.LOGTIME
        ulBadChecksumOld: _c_ese.uint32
        lGenMaxCommitted: _c_ese.int32
        bkinfoCopyPrev: _c_ese.BKINFO
        bkinfoDiffPrev: _c_ese.BKINFO
        bkinfoTypeCopyPrev: _c_ese.BKINFOTYPE
        bkinfoTypeDiffPrev: _c_ese.BKINFOTYPE
        ulIncrementalReseedCount: _c_ese.uint32
        logtimeIncrementalReseed: _c_ese.LOGTIME
        ulIncrementalReseedCountOld: _c_ese.uint32
        ulPagePatchCount: _c_ese.uint32
        logtimePagePatch: _c_ese.LOGTIME
        ulPagePatchCountOld: _c_ese.uint32
        qwSortVersion: _c_ese.uint64
        logtimeDbscanPrev: _c_ese.LOGTIME
        logtimeDbscanStart: _c_ese.LOGTIME
        pgnoDbscanHighestContinuous: _c_ese.uint32
        lGenRecovering: _c_ese.int32
        ulExtendCount: _c_ese.uint32
        logtimeLastExtend: _c_ese.LOGTIME
        ulShrinkCount: _c_ese.uint32
        logtimeLastShrink: _c_ese.LOGTIME
        logtimeLastReAttach: _c_ese.LOGTIME
        lgposLastReAttach: _c_ese.LGPOS
        ulTrimCount: _c_ese.uint32
        signDbHdrFlush: _c_ese.SIGNATURE
        signFlushMapHdrFlush: _c_ese.SIGNATURE
        lGenMinConsistent: _c_ese.int32
        ulDaeUpdateMinor: _c_ese.uint32
        efvMaxBinAttachDiagnostic: _c_ese.uint32
        pgnoDbscanHighest: _c_ese.uint32
        lgposLastResize: _c_ese.LGPOS
        rgbReserved: __cs__.Array[_c_ese.uint8]
        filetype: _c_ese.uint32
        rgbReserved2: __cs__.Array[_c_ese.uint8]
        logtimeGenMaxRequired: _c_ese.LOGTIME
        lGenPreRedoMinConsistent: _c_ese.int32
        lGenPreRedoMinRequired: _c_ese.int32
        signRBSHdrFlush: _c_ese.SIGNATURE
        ulRevertCount: _c_ese.uint32
        logtimeRevertFrom: _c_ese.LOGTIME
        logtimeRevertTo: _c_ese.LOGTIME
        ulRevertPageCount: _c_ese.uint32
        lgposCommitBeforeRevert: _c_ese.LGPOS
        @overload
        def __init__(
            self,
            ulChecksum: _c_ese.uint32 | None = ...,
            ulMagic: _c_ese.uint32 | None = ...,
            ulVersion: _c_ese.uint32 | None = ...,
            attrib: _c_ese.int32 | None = ...,
            dbtimeDirtied: _c_ese.int64 | None = ...,
            signDb: _c_ese.SIGNATURE | None = ...,
            dbstate: _c_ese.uint32 | None = ...,
            lgposConsistent: _c_ese.LGPOS | None = ...,
            logtimeConsistent: _c_ese.LOGTIME | None = ...,
            logtimeAttach: _c_ese.LOGTIME | None = ...,
            lgposAttach: _c_ese.LGPOS | None = ...,
            logtimeDetach: _c_ese.LOGTIME | None = ...,
            lgposDetach: _c_ese.LGPOS | None = ...,
            dbid: _c_ese.uint32 | None = ...,
            signLog: _c_ese.SIGNATURE | None = ...,
            bkinfoFullPrev: _c_ese.BKINFO | None = ...,
            bkinfoIncPrev: _c_ese.BKINFO | None = ...,
            bkinfoFullCur: _c_ese.BKINFO | None = ...,
            m_ulDbFlags: _c_ese.uint32 | None = ...,
            m_rgbDbFlags: __cs__.Array[_c_ese.uint8] | None = ...,
            objidLast: _c_ese.uint32 | None = ...,
            dwMajorVersion: _c_ese.uint32 | None = ...,
            dwMinorVersion: _c_ese.uint32 | None = ...,
            dwBuildNumber: _c_ese.uint32 | None = ...,
            lSPNumber: _c_ese.int32 | None = ...,
            ulDaeUpdateMajor: _c_ese.uint32 | None = ...,
            cbPageSize: _c_ese.uint32 | None = ...,
            ulRepairCount: _c_ese.uint32 | None = ...,
            logtimeRepair: _c_ese.LOGTIME | None = ...,
            rgbReservedSignSLV: __cs__.Array[_c_ese.uint8] | None = ...,
            dbtimeLastScrub: _c_ese.int64 | None = ...,
            logtimeScrub: _c_ese.LOGTIME | None = ...,
            lGenMinRequired: _c_ese.int32 | None = ...,
            lGenMaxRequired: _c_ese.int32 | None = ...,
            cpgUpgrade55Format: _c_ese.int32 | None = ...,
            cpgUpgradeFreePages: _c_ese.int32 | None = ...,
            cpgUpgradeSpaceMapPages: _c_ese.int32 | None = ...,
            bkinfoSnapshotCur: _c_ese.BKINFO | None = ...,
            ulCreateVersion: _c_ese.uint32 | None = ...,
            ulCreateUpdate: _c_ese.uint32 | None = ...,
            logtimeGenMaxCreate: _c_ese.LOGTIME | None = ...,
            bkinfoTypeFullPrev: _c_ese.BKINFOTYPE | None = ...,
            bkinfoTypeIncPrev: _c_ese.BKINFOTYPE | None = ...,
            ulRepairCountOld: _c_ese.uint32 | None = ...,
            ulECCFixSuccess: _c_ese.uint32 | None = ...,
            logtimeECCFixSuccess: _c_ese.LOGTIME | None = ...,
            ulECCFixSuccessOld: _c_ese.uint32 | None = ...,
            ulECCFixFail: _c_ese.uint32 | None = ...,
            logtimeECCFixFail: _c_ese.LOGTIME | None = ...,
            ulECCFixFailOld: _c_ese.uint32 | None = ...,
            ulBadChecksum: _c_ese.uint32 | None = ...,
            logtimeBadChecksum: _c_ese.LOGTIME | None = ...,
            ulBadChecksumOld: _c_ese.uint32 | None = ...,
            lGenMaxCommitted: _c_ese.int32 | None = ...,
            bkinfoCopyPrev: _c_ese.BKINFO | None = ...,
            bkinfoDiffPrev: _c_ese.BKINFO | None = ...,
            bkinfoTypeCopyPrev: _c_ese.BKINFOTYPE | None = ...,
            bkinfoTypeDiffPrev: _c_ese.BKINFOTYPE | None = ...,
            ulIncrementalReseedCount: _c_ese.uint32 | None = ...,
            logtimeIncrementalReseed: _c_ese.LOGTIME | None = ...,
            ulIncrementalReseedCountOld: _c_ese.uint32 | None = ...,
            ulPagePatchCount: _c_ese.uint32 | None = ...,
            logtimePagePatch: _c_ese.LOGTIME | None = ...,
            ulPagePatchCountOld: _c_ese.uint32 | None = ...,
            qwSortVersion: _c_ese.uint64 | None = ...,
            logtimeDbscanPrev: _c_ese.LOGTIME | None = ...,
            logtimeDbscanStart: _c_ese.LOGTIME | None = ...,
            pgnoDbscanHighestContinuous: _c_ese.uint32 | None = ...,
            lGenRecovering: _c_ese.int32 | None = ...,
            ulExtendCount: _c_ese.uint32 | None = ...,
            logtimeLastExtend: _c_ese.LOGTIME | None = ...,
            ulShrinkCount: _c_ese.uint32 | None = ...,
            logtimeLastShrink: _c_ese.LOGTIME | None = ...,
            logtimeLastReAttach: _c_ese.LOGTIME | None = ...,
            lgposLastReAttach: _c_ese.LGPOS | None = ...,
            ulTrimCount: _c_ese.uint32 | None = ...,
            signDbHdrFlush: _c_ese.SIGNATURE | None = ...,
            signFlushMapHdrFlush: _c_ese.SIGNATURE | None = ...,
            lGenMinConsistent: _c_ese.int32 | None = ...,
            ulDaeUpdateMinor: _c_ese.uint32 | None = ...,
            efvMaxBinAttachDiagnostic: _c_ese.uint32 | None = ...,
            pgnoDbscanHighest: _c_ese.uint32 | None = ...,
            lgposLastResize: _c_ese.LGPOS | None = ...,
            rgbReserved: __cs__.Array[_c_ese.uint8] | None = ...,
            filetype: _c_ese.uint32 | None = ...,
            rgbReserved2: __cs__.Array[_c_ese.uint8] | None = ...,
            logtimeGenMaxRequired: _c_ese.LOGTIME | None = ...,
            lGenPreRedoMinConsistent: _c_ese.int32 | None = ...,
            lGenPreRedoMinRequired: _c_ese.int32 | None = ...,
            signRBSHdrFlush: _c_ese.SIGNATURE | None = ...,
            ulRevertCount: _c_ese.uint32 | None = ...,
            logtimeRevertFrom: _c_ese.LOGTIME | None = ...,
            logtimeRevertTo: _c_ese.LOGTIME | None = ...,
            ulRevertPageCount: _c_ese.uint32 | None = ...,
            lgposCommitBeforeRevert: _c_ese.LGPOS | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class PAGE_FLAG(__cs__.Flag):
        Root = ...
        Leaf = ...
        ParentOfLeaf = ...
        Empty = ...
        Repair = ...
        Primary = ...
        SpaceTree = ...
        Index = ...
        LongValue = ...
        NonUniqueKeys = ...
        NewRecordFormat = ...
        NewChecksumFormat = ...
        Scrubbed = ...

    class PGHDR(__cs__.Structure):
        checksum: _c_ese.int64
        dbtimeDirtied: _c_ese.int64
        pgnoPrev: _c_ese.uint32
        pgnoNext: _c_ese.uint32
        objidFDP: _c_ese.uint32
        cbFree: _c_ese.uint16
        cbUncommittedFree: _c_ese.uint16
        ibMicFree: _c_ese.uint16
        itagState: _c_ese.uint16
        fFlags: _c_ese.PAGE_FLAG
        @overload
        def __init__(
            self,
            checksum: _c_ese.int64 | None = ...,
            dbtimeDirtied: _c_ese.int64 | None = ...,
            pgnoPrev: _c_ese.uint32 | None = ...,
            pgnoNext: _c_ese.uint32 | None = ...,
            objidFDP: _c_ese.uint32 | None = ...,
            cbFree: _c_ese.uint16 | None = ...,
            cbUncommittedFree: _c_ese.uint16 | None = ...,
            ibMicFree: _c_ese.uint16 | None = ...,
            itagState: _c_ese.uint16 | None = ...,
            fFlags: _c_ese.PAGE_FLAG | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class PGHDR2(__cs__.Structure):
        rgChecksum: __cs__.Array[_c_ese.int64]
        pgno: _c_ese.uint32
        rgbReserved: __cs__.CharArray
        @overload
        def __init__(
            self,
            rgChecksum: __cs__.Array[_c_ese.int64] | None = ...,
            pgno: _c_ese.uint32 | None = ...,
            rgbReserved: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class TAG_FLAG(__cs__.Flag):
        Version = ...
        Deleted = ...
        Compressed = ...

    class TAG(__cs__.Structure):
        cb_: _c_ese.uint16
        ib_: _c_ese.uint16
        @overload
        def __init__(self, cb_: _c_ese.uint16 | None = ..., ib_: _c_ese.uint16 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    RECOFFSET: TypeAlias = _c_ese.uint16
    class RECHDR(__cs__.Structure):
        fidFixedLastInRec: _c_ese.uint8
        fidVarLastInRec: _c_ese.uint8
        ibEndOfFixedData: _c_ese.uint16
        @overload
        def __init__(
            self,
            fidFixedLastInRec: _c_ese.uint8 | None = ...,
            fidVarLastInRec: _c_ese.uint8 | None = ...,
            ibEndOfFixedData: _c_ese.uint16 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class TAGFLD_HEADER(__cs__.Flag):
        Invalid = ...
        LongValue = ...
        Compressed = ...
        Separated = ...
        MultiValues = ...
        TwoValues = ...
        Null = ...
        Encrypted = ...

    class FIELDFLAG(__cs__.Flag):
        NotNull = ...
        Version = ...
        Autoincrement = ...
        Multivalued = ...
        Default = ...
        EscrowUpdate = ...
        Finalize = ...
        UserDefinedDefault = ...
        TemplateColumnESE98 = ...
        DeleteOnZero = ...
        PrimaryIndexPlaceholder = ...
        Compressed = ...
        Encrypted = ...

    class JET_bitIndex(__cs__.Flag):
        Unique = ...
        Primary = ...
        DisallowNull = ...
        IgnoreNull = ...
        Clustered40 = ...
        IgnoreAnyNull = ...
        IgnoreFirstNull = ...
        LazyFlush = ...
        Empty = ...
        Unversioned = ...
        SortNullsHigh = ...
        Unicode = ...
        Tuples = ...
        TupleLimits = ...
        CrossProduct = ...
        KeyMost = ...
        DisallowTruncation = ...
        NestedTable = ...
        DotNetGuid = ...
        ImmutableStructure = ...

    class IDBFLAG(__cs__.Flag):
        Unique = ...
        AllowAllNulls = ...
        AllowFirstNull = ...
        AllowSomeNulls = ...
        NoNullSeg = ...
        Primary = ...
        LocaleSet = ...
        Multivalued = ...
        TemplateIndex = ...
        DerivedIndex = ...
        LocalizedText = ...
        SortNullsHigh = ...
        UnicodeFixupOn_Deprecated = ...
        CrossProduct = ...
        DisallowTruncation = ...
        NestedTable = ...

    class IDXFLAG(__cs__.Flag):
        ExtendedColumns = ...
        DotNetGuid = ...

# Technically `c_ese` is an instance of `_c_ese`, but then we can't use it in type hints
c_ese: TypeAlias = _c_ese

ulDAEMagic: int
pgnoFDPMSO: int
pgnoFDPMSO_NameIndex: int
pgnoFDPMSO_RootObjectIndex: int
pgnoFDPMSOShadow: int

JET_coltyp: TypeAlias = c_ese.JET_coltyp
JET_bitIndex: TypeAlias = c_ese.JET_bitIndex
SYSOBJ: TypeAlias = c_ese.SYSOBJ
PAGE_FLAG: TypeAlias = c_ese.PAGE_FLAG
TAG_FLAG: TypeAlias = c_ese.TAG_FLAG
TAGFLD_HEADER: TypeAlias = c_ese.TAGFLD_HEADER
CODEPAGE: TypeAlias = c_ese.CODEPAGE
COMPRESSION_SCHEME: TypeAlias = c_ese.COMPRESSION_SCHEME
FIELDFLAG: TypeAlias = c_ese.FIELDFLAG
IDBFLAG: TypeAlias = c_ese.IDBFLAG
IDXFLAG: TypeAlias = c_ese.IDXFLAG
